[project]
name = "bsm2-python"
version = "0.1.0"
description = "A Python implementation of Benchmark Simulation Models 1 and 2 to simulate wastewater treatment plants."
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pytest"
]